### ISSUE TITLE
Blank page with Docker+Traeffik+Https

### ISSUE THREAD

**Issue by fabthegreat** [Nordaaker/convos#447]
I try to run the convos docker container behing traefik reverse proxy.
No pb to access convos with http, however it prints a blank page when I want to access through https (my other https service has no issue with traefik).
When I display source code of the page it tells:

```
<noscript>
      <p class="error">
        Javascript is disabled, so Convos cannot start. Please enable Javascript and try again.
      </p>
      <p>
        <a class="btn" href="/">Try again</a>
        <a class="btn is-hallow" href="mailto:root@localhost">Contact admin</a>
      </p>
</noscript>
```

Don't know if this is really an issue with javascript because it works well with http...

Also, chrome tells me that js sources are not authenticated...

It fails in a same manner with firefox, chrome, edge.

Where the issue would come from?

**Comment by jhthorsen** [comment]
Today is the first time I’ve heard about traefik, so I can’t really tell you how to set it up, but maybe you can extract the information from https://convos.by/doc/faq.html#can-convos-run-behind-behind-my-favorite-web-server and apply it to your server? Please pay attention to the environment variables and headers mentioned in the faq.

**Comment by fabthegreat** [comment]
Thanks for the link! I will check carefully and come back to you if any additional issue.

**Comment by kosssi** [comment]
@fabthegreat can you describe how you fix it? I have same error ;)

**Comment by fabthegreat** [comment]
Hello,
no I never achieved to fix it unfortunately. So I gave up this solution...too bad, it seemed promising. If you achieve something please let me know.

**Comment by jhthorsen** [comment]
Please share the config for traefik directly in the issue if it's small, or in a pastebin. Maybe I can understand what is missing. The only thing I can think of (which is mentioned in the link I shared) is that there's something wrong with the `X-Request-Base` header - Either missing or invalid.

**Comment by kosssi** [comment]
Here is my config:

```yml
version: "3.7"

volumes:
  convos:
    name: convos

networks:
  default:
    name: traefik

services:
  convos:
    container_name: convos
    image: registry.***.***/convos
    hostname: convos.***.***
    restart: always
    volumes:
      - convos:/data
    environment:
      TZ: Europe/Paris
      CONVOS_ORGANIZATION_NAME: My Organization
      CONVOS_ORGANIZATION_URL: https://***.***
      CONVOS_CONTACT: simon@***.***
      CONVOS_REVERSE_PROXY: '1'
      CONVOS_DEBUG: 'true'
      CONVOS_SECURE_COOKIES: 'true'
    # command: daemon --listen https://*:3000
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'traefik'
      traefik.http.routers.convos.rule: 'Host(`convos.***.***`)'
      traefik.http.routers.convos.entrypoints: 'websecure'
      traefik.http.routers.convos.tls.certResolver: 'letsencrypt'
      traefik.http.middlewares.convos.headers.customrequestheaders.Host: 'https://convos.***.***/'
      traefik.http.middlewares.convos.headers.customrequestheaders.X-Request-Base: 'https://convos.***.***/'
      traefik.http.middlewares.convos.headers.customrequestheaders.X-Forwarded-Proto: 'https'
```

When I arrive on `https://convos.***.***/`, one request is `http://convos.***.***/login` without the `s` of `https`, I don't understand why.

I'm testing The Lounge and now Kiwi IRC ;)
