### ISSUE TITLE
CONVOS_LOCAL_SECRET not docummented

### ISSUE THREAD

**Issue by zexa** [Nordaaker/convos#518]
**Describe the bug**
The CONVOS_LOCAL_SECRET env var is not available inside the convos docker container, nor is it docummented, introducing unnecessary confusion in the documentation.

**To Reproduce**
1. Try to follow password reset instructions
2. Notice the invite generation command asks you for `X-Local-Secret:YOUR_LOCAL_SECRET`
3. Notice that you're supposed to enter the `CONVOS_LOCAL_SECRET` env var instead of `YOUR_LOCAL_SECRET`
4. Notice that the `CONVOS_LOCAL_SECRET` env var is not docummented in https://convos.chat/doc/config
5. Try to look at your docker-compose file for such an env variable anyways
6. Notice that you haven't set such a variable inside your docker-compose file either.
7. Try to `echo $CONVOS_LOCAL_SECRET` inside of the convos container
8. Notice that such variable is not set inside the container anyways.

**Expected behavior**
`$CONVOS_LOCAL_SECRET` being automatically generated and available from the container if such variable is not set inside `docker-compose.yaml`.

If such solution is not possible, than at the very least documentation in https://convos.chat/doc/config mentioning that it is safe to add such an env variable to the configuration once convos has been initialized.

**Screenshots**

**Environment:**
```
version: '3'
services:
  convos:
    image: nordaaker/convos:release-4.33
    restart: always
    container_name: convos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convos.rule=Host(`convos.zexa.xyz`)"
      - "traefik.http.services.convos.loadBalancer.server.port=3000"
    volumes:
      - ./mount/convos:/data
    ports:
      - 3000:3000
    environment:
      - CONVOS_REVERSE_PROXY=1
      - VIRTUAL_HOST=zexa.xyz
      - MOJO_REVERSE_PROXY=1
      - CONVOS_REQUEST_BASE=https://convos.zexa.xyz/
    networks:
      - web

networks:
  web:
    external: true
```

**Additional context**
